#
# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#

version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-zts-node-browsers-legacy
    working_directory: ~/repo

    steps:
      - checkout
      
      - run: sudo chmod -R 777 /usr/lib /usr/include
      
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-

      # - restore_cache:
      #     keys:
      #     - libphpcpp-so

      - run: php build.php
      - run: make -j 4
      - run: php -d "extension=$(pwd)/teaai.so" main.php

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # - save_cache:
      #     paths:
      #       - /tmp/phpcpp
      #       - /usr/include/phpcpp
      #       - /usr/include/phpcpp.h
      #       - /usr/lib/libphpcpp.a
      #       - /usr/lib/libphpcpp.so
      #       - /usr/lib/libphpcpp.so.2.1
      #       - /usr/lib/libphpcpp.a.2.1.1
      #       - /usr/lib/libphpcpp.so.2.1.1
      #     key: libphpcpp-so

      - run: php ~/repo/php_syntax_checker.php
      - run: php ~/repo/vendor/bin/phpunit
      - run: php ~/repo/deploy.php